### ISSUE TITLE
Better error handling with tables: error messages should be specific

### ISSUE THREAD

**Issue by john-ross** [concordion/concordion-net#10]
currently often there is only a generic error message - similar to:
"The <table> 'execute' command only supports rows with an equal number of columns."
Such error messages are printed in the html test reports when different types of errors occur (e.g. see https://groups.google.com/forum/#!topic/concordion-for-net/Y6V8xjBB9Uc)

Error messages should describe the problem at hand and provide hints where to search for a problem.

**Comment by ShaKaRee** [comment]
improved reporting available:
https://github.com/concordion/concordion-net/pull/21
