### ISSUE TITLE
Will we be able to write and share extensions?

### ISSUE THREAD

**Issue by JulianMay** [concordion/concordion-net#12]
As far as i can tell, there is no support for extensions in Concordion.Net.
I have been using hidden span tags to isolate tests in transactions and embedded javascript to"html'ify" encoded output from helper classes, including rescource file helper and auto-generated links to related specifications. 
Theese are features I feel would go nicely in extensions, and using hooks like in the java Concordion, they could have been written much cleaner and less intrusive.
So I'm just wondering if this (Extension API) is even on the pipeline yet?

**Comment by ShaKaRee** [comment]
pull request for support of Concordion extension API in Concordion.NET has been merged:
https://github.com/concordion/concordion-net/pull/18
extension API will be available in next release of Concordion.NET (v1.2.0)
