### ISSUE TITLE
Update to NUnit 2.6.4

### ISSUE THREAD

**Issue by PapaMufflon** [concordion/concordion-net#23]
The NuGet package of concordion-net requires NUnit 2.6.3. Can you update to NUnit 2.6.4?

**Comment by ShaKaRee** [comment]
Thank you for this request. Concordion.NET will be updated to NUnit 2.6.4 with the next release hopefully in the next weeks.

**Comment by PapaMufflon** [comment]
Sweet :)

**Comment by ShaKaRee** [comment]
the update to NUnit 2.6.4 is on the way :-)
https://github.com/concordion/concordion-net/pull/25
